### ISSUE TITLE
Wrong radius and distance between buttons

### ISSUE THREAD

**Issue by AlexOg37** [AlexOg37/MobileGuestList#20]
Steps:
- go to contest selection page
- choose BOOK FAIR 2015 contest
- click generate guest list

AR:
- buttons have wrong radius and distance between buttons

ER:
- radius and distance between buttons should be like in design

PS radius should be increased for all buttons 

![](http://i.snag.gy/4aYSa.jpg)

**Comment by DmytroA** [comment]
start

**Comment by DmytroA** [comment]
fixed

**Comment by AlexOg37** [comment]
review:
