### ISSUE TITLE
Wrong view of generate guest list button

### ISSUE THREAD

**Issue by AlexOg37** [AlexOg37/MobileGuestList#22]
Steps:
- go to Guest Selection page

AR:
- there is a button with text "Generate Guest List" without exclamation point "!" in the end and in one line

ER:
- according to tech spec doc design text should be in two lines and with exclamation point "!" in the end

![](http://i.snag.gy/m7bHD.jpg)

PS: try to find more similar font

**Comment by DmytroA** [comment]
start\

**Comment by DmytroA** [comment]
fixed
P.S looking for similar font

**Comment by AlexOg37** [comment]
still it's wrong font (
but it's not important for now
