### ISSUE TITLE
guest list page does not save the checked state of guests

### ISSUE THREAD

**Issue by AlexOg37** [AlexOg37/MobileGuestList#25]
steps:
- open guest list page
- make changes
- reload page

AR:
- initial state is loaded

ER:
- changed state is saved and loaded

**Comment by DmytroA** [comment]
скачал последнюю версию и сделал все шаги, но у меня работает все правильно. Затрудняюсь овтетить в чем проблема пока

**Comment by AlexOg37** [comment]
the same bug is on contest list page when you try to change contest selection
