### ISSUE TITLE
#31 If there are no records found, pop up a message

### ISSUE THREAD

**Issue by DmytroA** [AlexOg37/MobileGuestList#31]
I picked COUNTY FAIR 2015 FAMILY 4 PACK PASSES and since there are no records found, we should have this happen (per the spec) instead of it just saying Total Attended 0/0. If there are no records found, pop up a message that says “Sorry, there are no listeners on this guest list.” When the user clears the message they are still on the Guest List Contest Selection Page so they can choose another contest from the drop down list.

**Comment by DmytroA** [comment]
finished

**Comment by AlexOg37** [comment]
chrome: alert does not appear
