### ISSUE TITLE
Add script for hiding attended guest

### ISSUE THREAD

**Issue by AlexOg37** [AlexOg37/MobileGuestList#4]
Implement js script that will respond to click on Hide Attendees slide on guest list page

**Comment by DmytroA** [comment]
start

**Comment by DmytroA** [comment]
finished

**Comment by AlexOg37** [comment]
review:
- replace all code from hide_attendes.js to guestlist.js. delete hide_attendes.js, remove all references on this file
- put string "You must first select a contest" in constant variable
- return code <b>@ViewBag.Contest.Name</b> on Guest/Index page. the name of contest should be displayed on this page

**Comment by AlexOg37** [comment]
bug steps:
- go to guest list page
- turn on Hide Attendees
- check on some of guests
AR:
- nothing is changed
ER:
- checked guest should disappear

**Comment by DmytroA** [comment]
fixed
