### ISSUE TITLE
Wrong behaviour of all buttons

### ISSUE THREAD

**Issue by AlexOg37** [AlexOg37/MobileGuestList#6]
Steps:
- get on to Prize Distribution page
- click down on any button and hold the mouse button
- move mouse outside the button
- leave the mouse button

AR:
- button become bigger
- in the end of button text appeare input cursor

ER:
- after clicking button save its size
- after clickin there is no input cursor inside the button

**Comment by DmytroA** [comment]
start

**Comment by DmytroA** [comment]
fixed
